[package]
name = "github_pr_merge"
type = "bin"
authors = ["Mach 34"]
compiler_version = ">=0.34.0"

[dependencies]
noir_rsa = { tag = "v0.3.0", git = "https://github.com/noir-lang/noir_rsa", directory = "lib" }
string_search = { tag = "v0.2.0", git = "https://github.com/olehmisar/noir_string_search/" }