[package]
name = "zkemail.nr"
type = "bin"
authors = ["Mach 34"]
compiler_version = ">=0.34.0"

[dependencies]
bignum = {tag = "v0.3.3", git = "https://github.com/noir-lang/noir-bignum"}
noir_rsa = { tag = "v0.3.0", git = "https://github.com/noir-lang/noir_rsa", directory = "lib" }
# string_search = { tag = "v0.1", git = "https://github.com/noir-lang/noir_string_search"  }